# Add helm repo for Cilium: helm repo add cilium https://helm.cilium.io
# Install Cilium with Helm: helm install cilium cilium/cilium --version v1.18.0-rc.0 --namespace kube-system -f cilium-values.yaml
# helm upgrade --install cilium cilium/cilium --version v1.18.0-rc.0 --namespace kube-system -f cilium-values.yaml

debug:
  enabled: true

routingMode: native

ipv6:
  enabled: true

bgpControlPlane:
  enabled: true

ipv4NativeRoutingCIDR: 10.0.0.0/16
ipv6NativeRoutingCIDR: fd00::/16

ipam:
  mode: kubernetes

k8s:
  requireIPv4PodCIDR: true
  requireIPv6PodCIDR: true

operator:
  enabled: true
  replicas: 1

externalIPs:
  enabled: true