apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: k8s
networking:
  ipFamily: dual
  disableDefaultCNI: true
#  podSubnet: "10.0.0.0/16,fe80:10:0::/63"
#  serviceSubnet: "10.2.0.0/16,fd00:10:2::/108"
#  apiServerAddress: "127.0.0.1"
#  apiServerPort: 6443
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 31235
      hostPort: 31235
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-ip: "10.0.0.2,fe80:10:0:0::2"
            node-labels: "rack=rack1"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-ip: "10.0.1.2,fe80:10:0:1::2"
            node-labels: "rack=rack1"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-ip: "10.0.2.2,fe80:10:0:2::2"
            node-labels: "rack=rack2"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-ip: "10.0.3.2,fe80:10:0:3::2"
            node-labels: "rack=rack3"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-ip: "10.0.4.2,fe80:10:0:4::2"
            node-labels: "rack=rack3"
