# Add helm repo for Cilium: helm repo add isovalent https://helm.isovalent.com
# Install Cilium with Helm: helm install cilium isovalent/cilium --version <add version here> --namespace kube-system -f values.yaml

debug:
  enabled: true

routingMode: native

ipv6:
  enabled: true

bgpControlPlane:
  enabled: true

ipv4NativeRoutingCIDR: 10.0.0.0/8
ipv6NativeRoutingCIDR: fe80::/16

ipam:
  mode: kubernetes

k8s:
  requireIPv4PodCIDR: true
  requireIPv6PodCIDR: true

operator:
  enabled: true
  replicas: 1