# Apply kubectl apply -f service/load-balancer.yaml

---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ip-pool-blue"
  labels:
    bgp: blue
spec:
  blocks:
    - cidr: "20.0.10.0/24"
    - cidr: "2004::0/64"
  serviceSelector:
    matchExpressions:
      - {key: bgp, operator: In, values: [blue]}

---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ip-pool-red"
  labels:
    bgp: red
spec:
  blocks:
    - cidr: "20.1.10.0/24"
    - cidr: "2004:1::0/64"
  serviceSelector:
    matchExpressions:
      - {key: bgp, operator: In, values: [red]}